spring.application.name=practica2

spring.datasoruce.url=postgresql://localhost:5432/practic_jwt2
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update

jwt.secret=UnaContrasenaMuySeguraParaFirmarElJwtYQueSeaLarga123456789
jwt.expiration=86400000